language: python
python:
  - "3.6"

services:
  - mongodb

before_script:
  - mongo --eval 'rs.status()'

install:
  - pip install pylint
  - pip install -r requirements.txt

script:
  - pylint --errors-only macsy
